### PR TITLE
Correct bogo checkout

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/rustls/rustls/pull/820#issuecomment-922354785

### CODE REVIEW

**Comment by gliptak** [comment]
@ctz thank you for the pointer. the build is green

**Comment by djc** [comment]
We should remove the command again that rebuilds `go.sum`.

**Comment by gliptak** [comment]
@djc updated

**Comment by ctz** [comment]
Thanks, I merged the original commit here along with a straight revert of 9407ada7

**Pull request closed without merging**
