### PR TITLE
list ECH as a feature, fix some low-hanging nightly clippy findings.

### PR DESCRIPTION
**Pull request by cpu**
Just a handful of small & unremarkable tweaks.

### CODE REVIEW

**Review by ctz — APPROVED** [review]

**Comment by cpu** [comment]
I'll wait to merge this until after #2156.

**Review by djc — APPROVED** [review]

**Comment by cpu** [comment]
FYI: tacked on one more commit after updating my local toolchain, https://github.com/rustls/rustls/pull/2157/commits/3bf735729368717f2af973aa1ecb24c693660d99 The elided lifetime changes all make sense to me, but could use a 2nd set of eyes.

Will rebase on `main` shortly.

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
> I'll wait to merge this until after #2156.

Not sure why we'd exclude this from the release?

**Comment by ctz** [comment]
Yes, let's merge this. Minor delay on 0.23.15 while I understand the benchmarking differences between machines.

**Pull request merged**
