### PR TITLE
Bump Golang to 1.17 in GHA

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Review by ctz — APPROVED** [review]

**Comment by djc** [comment]
@ctz I'm confused: this looks like it broke bogo in CI. Do you plan to mitigate this?

**Comment by ctz** [comment]
Er, yes, I misread the status of this PR and merged it prematurely. Currently looking at it.

**Comment by gliptak** [comment]
@ctz how https://github.com/rustls/boringssl (?) pulled into this build tree?

**Comment by ctz** [comment]
It happens in this script: https://github.com/rustls/rustls/blob/main/bogo/fetch-and-build

Hm, that sparse checkout business is missing out go.sum; that sounds like it might be a problem.

**Pull request merged**
