### PR TITLE
Expose UnknownExtensions fields & to use in projects.

### PR DESCRIPTION
**Pull request by gituser-rs**
Hey. I am working on a Anti-Bot project and I need to access unknown extension fields to check if some extension is present. 

For example:
```
if let ClientExtension::Unknown(UnknownExtension {
    typ: ExtensionType::Unknown(28),
    ..
}) = ext
{
    Some(true)
} else {
    None
}
```

These fields & enums is private so I hope we can make them public 😃

### CODE REVIEW

**Review by djc — APPROVED** [review]
Seems harmless, I guess?

**Comment by ctz** [comment]
The `internals` module and everything inside is not really intended for use in anything other than our tests, and is outside the API that we check for semver-compatible changes. So if you are using this in a downstream crate, that will be extremely fragile and I suggest you vendor this crate (where you can make this change).

**Comment by gituser-rs** [comment]
> The `internals` module and everything inside is not really intended for use in anything other than our tests, and is outside the API that we check for semver-compatible changes. So if you are using this in a downstream crate, that will be extremely fragile and I suggest you vendor this crate (where you can make this change).

That's the only change i need. I don't think creating fork for such type of change is a good idea tbh.

**Comment by djc** [comment]
> The `internals` module and everything inside is not really intended for use in anything other than our tests, and is outside the API that we check for semver-compatible changes. So if you are using this in a downstream crate, that will be extremely fragile and I suggest you vendor this crate (where you can make this change).

To be fair, it also changes only pretty rarely so it might just work out okay for a long time (but, no guarantees -- might want to pin those dependencies).

**Comment by ctz** [comment]
I think I've said my piece on this. Note that I still plan to return to #1475 at some point, and that would remove `UnknownExtension` and also make it structurally hard to reinstate later.

**Review by ctz — CHANGES_REQUESTED** [review]
Please run `cargo fmt`

**Comment by cpu** [comment]
I'm worried merging this will send the wrong message to consumers, both about the scope of the `rustls` project and the `internals` module. I think users wanting to interrogate low-level details of the handshake are better served by using a crate tailored for that (e.g. [tls-parser](https://github.com/rusticata/tls-parser)). Adding this capability, and then turning around and removing it in subsequent refactoring seems like it will only cause strife and prolong future discussions about exposing other properties beyond unknown extensions that occur with some frequency.

**Comment by djc** [comment]
I'm okay with closing this, FWIW -- had forgotten about the extension refactoring work that will get rid of this. We should get #1475 merged already...

**Comment by cpu** [comment]
Thank you for the contribution. Apologies that this isn't the outcome you were hoping for, but I think there are options available to you. You might also be interested in pursing this change with a fork like https://github.com/3andne/craftls that has more appetite for API changes tailored to more niche use-cases.

**Pull request closed without merging**
