### PR TITLE
Cargo.lock: update semver compatible deps

### PR DESCRIPTION
**Pull request by cpu**
Replaces https://github.com/rustls/rustls/pull/1871

* async-trait 0.1.78 -> 0.1.79
* rayon 1.9.0 -> 1.10.0
* rustls-pki-types 1.10.3 -> 1.10.4
* regex 1.10.3 -> 1.10.4
* base64 0.21.7 -> 0.22

### CODE REVIEW

**Comment by djc** [comment]
So why aren't we updating to base64 0.22?

**Comment by cpu** [comment]
> So why aren't we updating to base64 0.22?

`cargo update -p base64` gives me no `Cargo.lock` diff. Same for `env_logger`. 

You want to see the `Cargo.toml` versions manually incremented?

**Comment by djc** [comment]
I would expect a change to update `Cargo.toml` in for the dev-dependency in rustls and in openssl-tests.

**Comment by cpu** [comment]
Added a separate commit for the `base64` update. `env_logger` remains at 0.10 to avoid the 1.71 MSRV associated with 0.11.

I'll make sure to include these dev dep updates as part of the regular process for future PRs.

**Comment by cpu** [comment]
>  as part of the regular process

Though, now that we know the upstream dependabot folks aren't likely to make their automation work the way we want I'm perhaps more open to the idea of using [renovatebot](https://docs.renovatebot.com/) like @ctz suggested at one point.

**Review by djc — APPROVED** [review]
FWIW, I also think having one commit per semver-compatible dep isn't really worth it.

For Renovate, the rustup repo has a decent setup which we could steal from.

**Pull request merged**
