### PR TITLE
Correct complete_io behaviour when close_notify alert is received (0.20 edition) 

### PR DESCRIPTION
**Pull request by jiahaoliang**
backporting https://github.com/rustls/rustls/pull/1907 to 0.20 edition

### CODE REVIEW

**Comment by jiahaoliang** [comment]
@ctz @cpu Dear maintainers, we have been considering backporting this change to 0.20.x version. Would you be willing to take a moment to review the changes and approve the workflows? Thank you.

**Comment by djc** [comment]
Why can't you upgrade to 0.21?

**Comment by jiahaoliang** [comment]
> Why can't you upgrade to 0.21?
@djc we would like to make minimal changes to our legacy codebase if possible. We did upgrade our master branch to lastest version which required quite a bit of changes.

**Comment by ctz** [comment]
I would suggest vendoring 0.20 if you need to maintain an old version. 0.20 is outside our support window: https://github.com/rustls/rustls/blob/main/SECURITY.md#supported-versions

**Comment by jiahaoliang** [comment]
> I would suggest vendoring 0.20 if you need to maintain an old version. 0.20 is outside our support window: https://github.com/rustls/rustls/blob/main/SECURITY.md#supported-versions

@ctz Sure, we're happy to proceed with vendoring and patching 0.20 locally to meet our specific needs. The PR was submitted with the intention of potentially benefiting other users who may still be using 0.20.

Please feel free to close the PR if upstream has decided not to accept further PRs for the 0.20.

**Comment by cpu** [comment]
> The PR was submitted with the intention of potentially benefiting other users who may still be using 0.20.

Thank you, that's thoughtful :+1: 

> 0.20 is outside our support window:

I agree and think we shouldn't merge this. If we merge it without releasing it, then it won't be of much help. If we merge it and release it, then our support policy slips into "everything, forever" and that's not tenable. If we close this PR the commit is still available for anyone that needs it for their own vendored solution.

**Pull request closed without merging**
