### PR TITLE
Defer opening key log file until writing to it

### PR DESCRIPTION
**Pull request by djc**
As suggested in #868.

### CODE REVIEW

**Comment by djc** [comment]
(clippy issues fixed in #867.)

**Comment by LPardue** [comment]
thank you!

**Review by ctz — APPROVED** [review]

**Comment by briansmith** [comment]
Technically, this is a technically a breaking change, for the following scenerios:
* The application implements sandboxing. They want to have the sandbox block opening files, but they want to support this feature, so they configure the key log before enabling the sandbox, which they do before they make any TLS connections. Before, this strategy worked, AFAICT. Now, I think it doesn't, because the file won't be opened until at least the first TLS connection, at which time the sandbox will block the opening.
* For similar reasons, if the current working directory changes between enabling the key logging and the first attempt to log, then a different file will be opened and written to.
* If the application tries to `unlink()` after configuring the logging but before the first thing is logged.

That's not to say the change shouldn't be made, but is good to note it.

**Comment by briansmith** [comment]
This was reverted in PR #926.

**Pull request merged**
