### PR TITLE
Add a simple mTLS example

### PR DESCRIPTION
**Pull request by uggla**
Hello,

First thanks for all the hard work on rustls. It is great !

Here is a small example doing mTLS with rustls.
I spent some time understanding how to load certs from pem file and mainly with #380 issue.
So this is an example for beginner like me to have a straight working example.

### CODE REVIEW

**Comment by briansmith** [comment]
First, @uggla, are you still interested in this?

I'm curious about what @djc and @ctz think about this.

I wonder if we should avoid having a bunch of little demo apps that each demonstrate a different facet, and instead demonstrate this kind of thing by adding flags to `tlsclient` and `tlsserver`.

**Comment by djc** [comment]
I don't like example proliferation. This might be a better as an additional option to the existing client, and perhaps additional clarifications in the reference documentation if we think the current approach to mTLS is hard to learn.

**Comment by uggla** [comment]
Hello @briansmith, @djc

I'm used to looking at examples and I like if I can find one really close to what I need.
However, if you judge this is not a proper approach to document things and prefer another way, I'll be happy to help.

**Comment by briansmith** [comment]
I looked at tlsclient and I see it already has:
```
    --auth-key KEY      Read client authentication key from KEY.
    --auth-certs CERTS  Read client authentication certificates from CERTS.
                        CERTS must match up with KEY.
```
And I looked at tlsserver and it has:
```
    --auth CERTFILE     Enable client authentication, and accept certificates
                        signed by those roots provided in CERTFILE.
```

Given this, I'd lean towards trying to clean up tlsclient and tlsserver code to make it easier to read, and making the comments in it much more educational/tutorial in nature, so that those two programs can serve as the example.

Also, pretty much everybody is using tokio-rustls or equivalent, AFAICT, so IMO more people would benefit from a demo that uses tokio-rustls--perhaps in that repo.

WDYT?

**Comment by djc** [comment]
Yes, let's close this in favor of improving existing examples/documentation.

**Pull request closed without merging**
