### PR TITLE
minor fix: fix comment that incorrectly says "google.com" instead of "rust-lang.org"

### PR DESCRIPTION
**Pull request by girlbuzz**

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Thanks!

**Comment by cpu** [comment]
Would you mind squashing your two commits into one?

**Review by djc — APPROVED** [review]

**Comment by cpu** [comment]
> I propose we use administrative merge to bypass the merge queue to allow using "Squash and merge"

Done.

Thanks again for the fix.

**Comment by girlbuzz** [comment]
apologies for not squashing it myself, I just wasn't on Github actively.

**Pull request merged**
