### PR TITLE
Add rustls-rustcrypto to the list of third-party providers

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
As my work has finally been merged, I would like to add it to the shortlist. Also, this provider is almost no-std ready, once #1399 kicked off, but I'm not sure whether we should mention this.

---
N.B. Again, I do not recommend using this provider, until we can formally verify everything, but so far it works _practically_, I tested this on a customized [arti client](https://gitlab.torproject.org/tpo/core/arti) (yep, for connecting to the Tor network), and it worked, but the only problem is Tor team doesn't let me contribute to their GitLab by not letting me create an account over. I'm trying my best to see if anyone has a connection to the Tor team, and urgh just let me submit that MR.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Review by cpu — DISMISSED** [review]
Thanks for the update PR :-)

> rustls / Check for documentation errors (pull_request) Failing after 2m

These edits need to be made in [lib.rs](https://github.com/rustls/rustls/blob/main/rustls/src/lib.rs) and then pulled into the README with the [`admin/pull-readme`](https://github.com/rustls/rustls/blob/main/admin/pull-readme) helper script.

**Comment by stevefan1999-personal** [comment]
@djc that bot is interesting. mind getting it to work with rustls-rustcrypto to see how much slower it is?

**Comment by djc** [comment]
See here for more context: https://ochagavia.nl/blog/continuous-benchmarking-for-rustls/.

**Comment by stevefan1999-personal** [comment]
So we just need to implement this...
https://github.com/rustls/rustls/blob/75edb20a1e6a894089516053348b6137a425b9b4/ci-bench/src/main.rs#L309-L320

**Comment by cpu** [comment]
> These edits need to be made in [lib.rs](https://github.com/rustls/rustls/blob/main/rustls/src/lib.rs) and then pulled into the README with the [admin/pull-readme](https://github.com/rustls/rustls/blob/main/admin/pull-readme) helper script.

@stevefan1999-personal Are you able to address this feedback and rebase the branch? It would be nice to get this small change merged soon.

**Comment by stevefan1999-personal** [comment]
> > These edits need to be made in [lib.rs](https://github.com/rustls/rustls/blob/main/rustls/src/lib.rs) and then pulled into the README with the [admin/pull-readme](https://github.com/rustls/rustls/blob/main/admin/pull-readme) helper script.
> 
> @stevefan1999-personal Are you able to address this feedback and rebase the branch? It would be nice to get this small change merged soon.

Sure! Let me get that done today after implementing the ticketeer

**Pull request merged**
