### PR TITLE
minor improvements to internal test imports

### PR DESCRIPTION
**Pull request by brodycj**

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Thanks

**Review by ctz — APPROVED** [review]

**Review by djc — APPROVED** [review]
I'd prefer to move in the direction of `super::enums` instead of `crate::msgs::enums`.

(For the future, also not sure if this kind of thing is really worth a PR on its own.)

**Comment by cpu** [comment]
> I would like to update this when I get a chance.

Let's close it for the meantime then. I don't think there's any value in having it left in draft status in the meantime, it just clutters up the PR list.

Thanks,

**Comment by brodycj** [comment]
I just tried to push an update on this but it is now closed and I cannot reopen it. Can we reopen this?

**Comment by cpu** [comment]
a

**Pull request closed without merging**
