### PR TITLE
Remove support for SCT stapling

### PR DESCRIPTION
**Pull request by ctz**

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
> compared to inclusion of SCTs in certificates

When I read this I wonder if/how rustls supports this. I suppose we don't? Why not? It's a bit fuzzy to me.

**Comment by cpu** [comment]
> I suppose we don't? Why not? It's a bit fuzzy to me.

I think one of the challenges we'd have to overcome is keeping the metadata for CT logs in sync and up to date, as well as matching the browser policies for the SCT requirements. E.g., when Google turned down a deprecated log list endpoint it wreaked havoc in the Android ecosystem because of a library that wasn't keeping pace with the ecosystem failing closed (https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/fX_AG-HUAQAJ)

**Review by cpu — APPROVED** [review]
Looks good, thanks!

@ctz Do you plan to archive the [sct.rs](https://github.com/rustls/sct.rs) repo as well? It might be a good idea to signal its not maintained anymore.

**Comment by ctz** [comment]
> > compared to inclusion of SCTs in certificates
> 
> When I read this I wonder if/how rustls supports this. I suppose we don't? Why not? It's a bit fuzzy to me.

I've added https://github.com/rustls/webpki/issues/105 to record that work.

**Comment by djc** [comment]
> > I suppose we don't? Why not? It's a bit fuzzy to me.
> 
> I think one of the challenges we'd have to overcome is keeping the metadata for CT logs in sync and up to date, as well as matching the browser policies for the SCT requirements. E.g., when Google turned down a deprecated log list endpoint it wreaked havoc in the Android ecosystem because of a library that wasn't keeping pace with the ecosystem failing closed (https://groups.google.com/a/chromium.org/g/ct-policy/c/zejEtWAJtEA/m/fX_AG-HUAQAJ)

So should we add a bit of explanation in the README/manual parts of the reference docs what is and isn't supported and why?

**Comment by cpu** [comment]
> Do you plan to archive the [sct.rs](https://github.com/rustls/sct.rs) repo as well? It might be a good idea to signal its not maintained anymore.
..
> I've added https://github.com/rustls/webpki/issues/105 to record that work.

Ah ok so maybe premature to shutter sct.rs then :+1:

**Pull request merged**
