### PR TITLE
Add end entity and client public keys in PEM format for testing

### PR DESCRIPTION
**Pull request by holodorum**
This PR adds public keys in PEM format for the end entity and client, useful to test the implementation of Raw Public Keys in https://github.com/rustls/rustls/pull/2062

### CODE REVIEW

**Review by ctz — APPROVED** [review]
(could squash these two commits; i could take it or leave it.)

**Comment by ctz** [comment]
(I think those benchmark results are a result of this branch being before the ticketer changes.)

**Comment by holodorum** [comment]
> (could squash these two commits; i could take it or leave it.)

Squashed the two commits

> (I think those benchmark results are a result of this branch being before the ticketer changes.)

I think you're right, I've synced the fork and rebased the branch.

**Comment by ctz** [comment]
I think this is low enough risk to merge with just my review.

**Pull request merged**
