### PR TITLE
Fix deprecation warnings for subjects() in tests

### PR DESCRIPTION
**Pull request by jsha**
Followup to https://github.com/rustls/rustls/pull/1064#issuecomment-1168462184

### CODE REVIEW

**Comment by djc** [comment]
Looks like it's time to bump the MSRV, can you do that in this PR?

Thanks for fixing this up!

**Comment by jsha** [comment]
The error appears to be in "plotters", which is a transitive dependency of "criterion", which is a dev-dependency. Rather than bumping the MSRV, perhaps we can exclude rustls/tests/benchmarks.rs when we run tests on the MSRV?

```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/plotters-0.3.2/Cargo.toml`
Caused by:
  feature `edition2021` is required
```

**Comment by djc** [comment]
I guess, but as far as I've seen the cat is out of the bag on 1.56.

**Comment by djc** [comment]
Issue in plotters: https://github.com/plotters-rs/plotters/issues/398.

**Comment by djc** [comment]
@jsha did you want to finish this up by updating the MSRV?

**Comment by jsha** [comment]
Yes. I thought I had already sent a PR updating the MSRV, but it looks like it never made it off my computer. Thanks for the ping.

**Comment by jsha** [comment]
Actually, MSRV was updated in #1083. This just needed to be rebased. That's now done and this is passing tests.

**Review by djc — APPROVED** [review]

**Pull request merged**
