### PR TITLE
add DerefMut to common state for UnbufferedConnectionCommon

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
This is needed because `CommonState::send_close_notify()` is needed to be called when you need to do `send_close_notify` for fatal case.

### CODE REVIEW

**Comment by ctz** [comment]
Is this so you can call `CommonState::send_close_notify()`? Because there is `queue_close_notify()` on the unbuffered WriteTraffic state.

**Comment by cpu** [comment]
>> Because there is queue_close_notify() on the unbuffered WriteTraffic state.
>>
> Exactly. I have to handle these cases:

I think the missing piece is why you can't use `queue_close_notify()` from `WriteTraffic` state for this. Can you be more explicit about that aspect?

**Review by cpu — APPROVED** [review]
I'm still not sure I understand the motivation fully, but I don't feel very strongly either.

> codecov/patch — 0.00% of diff hit (target 94.63%)

It would be nice to have a small smoketest to make sure we don't regress this by mistake.

Can you also squash your commits?

**Comment by cpu** [comment]
@stevefan1999-personal ping?

**Comment by djc** [comment]
Unless we have a clear(er) motivation I don't think we should merge this.

**Comment by cpu** [comment]
> Unless we have a clear(er) motivation I don't think we should merge this.

Agreed, and the OP isn't responding so let's close this for now.

**Pull request closed without merging**
