### PR TITLE
example client protover arg should allow multiple versions

### PR DESCRIPTION
**Pull request by tanyav2**
Fixes https://github.com/rustls/rustls/issues/855

### CODE REVIEW

**Review by thomwiggers — CHANGES_REQUESTED** [review]
This looks like the right solution, evidenced by the fact that `--suite` and `--proto` already do the same.

This should also be patched on the server side in `rustls-mio/examples/tlsserver.rs` though.

**Comment by djc** [comment]
Sounds good to me. @tanyav2 thanks for fixing this, are you up for fixing the server, too?

**Comment by tanyav2** [comment]
@djc @thomwiggers Fixed

**Review by thomwiggers — APPROVED** [review]

**Review by ctz — APPROVED** [review]
Thanks!

**Pull request merged**
