### PR TITLE
docs: move details ConnectionCommon -> Connection.

### PR DESCRIPTION
**Pull request by cpu**
Previously the `Connection` rustdoc comments were short and directed the reader to `ConnectionCommon` for most of the detail.

Since `ConnectionCommon` is largely a detail internal to Rustls this commit flips this pattern. The detailed doc comments are moved to the `Connection` type and the `ConnectionCommon` doc comments refer back to those.

Resolves https://github.com/rustls/rustls/issues/1272

### CODE REVIEW

**Review by jsha — APPROVED** [review]

**Comment by djc** [comment]
So the reason I did it this way is actually that `ClientConnection` and `ServerConnection`, which I think are more likely to be used in most applications than the `Connection` wrapper, sort of expose these methods through a `Deref<Target = ConnectionCommon<Data>>`. Therefore I actually think the `ConnectionCommon` versions of these methods are more likely to be read/referenced than the `Connection` version. So this was entirely on purpose.

**Comment by jsha** [comment]
Aha, now that you say that it totally makes sense, and I got mixed up about which type would more commonly be used by the user. So it seems Connection is meant to be used (via its `From<ClientConnection>` and `From<ServerConnection>` impls) by code that wishes to generalize across client vs server?

At any rate, @cpu sorry for the unnecessary work here.

**Comment by djc** [comment]
> So it seems Connection is meant to be used (via its `From<ClientConnection>` and `From<ServerConnection>` impls) by code that wishes to generalize across client vs server?

Yup. (You can also abstract over it, with something like `impl Deref<Target = ConnectionCommon<impl SideData>>`.)

**Comment by cpu** [comment]
> At any rate, @cpu sorry for the unnecessary work here.

Zero apologies needed :-) It was next to no work and I could/should have thought deeper about it myself. Glad we're all on the same page now :+1:

**Pull request closed without merging**
