### PR TITLE
Small refactors

### PR DESCRIPTION
**Pull request by liujustin604**
Use if let Some(x) instead of checking is_some() and then unwrapping inside the if statement

### CODE REVIEW

**Review by djc — APPROVED** [review]
Thanks, these are nice improvements!

**Comment by djc** [comment]
Just some small formatting fixes to apply.

**Review by cpu — APPROVED** [review]
LGTM mod [needing `rustfmt`](https://github.com/rustls/rustls/actions/runs/10969204174/job/30464587630?pr=2130)

Thanks!

**Comment by cpu** [comment]
Admin merged so I could squash the commits.

Thanks!

**Pull request merged**
