### PR TITLE
nit(ci): remove a trailing space from daily-tests.yml

### PR DESCRIPTION
**Pull request by brodycj**
TODO

- [x] ~~I would like to raise an issue to start linting non-source files such as Cargo & GitHub CI files in CI~~ ✅ - raised #2099 to track this
- ~~I would love to contribute a solution for this _CI improvement_, cannot promise when I may have time for this~~ ❌ _deferred for now_

---

I don't want to block merging this, thinking we should improve the automation in this area (if possible & anyone has time to deal with this)

### CODE REVIEW

**Review by cpu — APPROVED** [review]
Does a PR removing a single character need to be a draft? :zany_face:

**Comment by brodycj** [comment]
My apologies ... now ready for review ... already raised issue #2099 to go after the root cause 😄😄

**Comment by djc** [comment]
Please rebase to get rid of the merge commit.

**Comment by brodycj** [comment]
rebased thanks!

**Comment by brodycj** [comment]
Looks like there was a fuzz issue in CI: https://github.com/rustls/rustls/actions/runs/10621951781/job/29445121683?pr=2098

I have actually updated the title, will try another force-push to update the title in the commit message & see if this fuzz issue persists or goes away.

**Review by ctz — APPROVED** [review]

**Pull request merged**
